[package]
name = "snake_bin_std"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11.8"
snake_lib = { path = "../snake_lib/" }
slint = { version = "1.13.0", default-features = true}
rand = "0.9.1"